Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kxmlgui': '@stable'
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/plasma-framework': '@stable'    

Options:
  cmake-options: '-DBUILD_WITH_WEBENGINE=ON'
