macro(feature_note text state)
    if(${state})
        message(STATUS "${text} is supported")
    else()
        message(WARNING "${text} is not supported")
    endif()
endmacro()

macro(feature_notes a b c d)
    feature_note("Fetching pages with javascript" ${a})
    feature_note("Preview of fetched pages" ${b})
    feature_note("Multilingual preview of web pages" ${c})
    feature_note("Inspecting of web pages" ${c})
endmacro()
